version: '3.9'

services:
  db:
    container_name: bewise-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - ${SERVER_PORT-8000}:${EXTERNAL_PORT-8000}
    entrypoint: ["/code/entrypoint.sh"]
    depends_on:
      - db

volumes:
  postgres_data:
